language: node_js
sudo: required
services:
- mongodb
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm install -g npm
after_success:
  - npm run semantic-release
branches:
  except:
    - test
    - "/^v\\d+\\.\\d+\\.\\d+$/"
