language: node_js
sudo: false
services: mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm install -g npm5
  - npm5 install
after_success:
  - npm5 run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
