language: node_js
sudo: required
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get update
  - sudo apt-get install -y --allow-unauthenticated mongodb-org
  - npm install -g npm
after_success:
  - npm run semantic-release
branches:
  except:
    - test
    - "/^v\\d+\\.\\d+\\.\\d+$/"
